name: terraform-deploy

on:
  push:
    branches:
      - "prod-deployment"

permissions:
  id-token: write # This is required for requesting the JWT.
  contents: read  # This is required for actions/checkout.

jobs:
  tf-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.ECR_AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Format
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -input=false

      #   # On push to "prod-deployment"", deploy the Terraform infrastructure
      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/prod-deployment"' && github.event_name == 'push'
      #   run: terraform apply -auto-approve -input=false
